/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Kalkulator extends javax.swing.JFrame {

    String angka="";
    double angka1,angka2,jumlah; 
    int pilih;
    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        angka="";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextTampil = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bttntambah = new javax.swing.JButton();
        bttnkurang = new javax.swing.JButton();
        bttnbagi = new javax.swing.JButton();
        bttnkali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        bttnsamadengan = new javax.swing.JButton();
        bttnclear = new javax.swing.JButton();
        btnkoma = new javax.swing.JButton();
        btnpersen = new javax.swing.JButton();
        btnakar = new javax.swing.JButton();
        btnpangkat = new javax.swing.JButton();
        btnsisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);
        getContentPane().add(jTextTampil);
        jTextTampil.setBounds(30, 70, 350, 70);

        b1.setText("1");
        b1.setBorderPainted(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(30, 150, 60, 50);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(100, 150, 60, 50);

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(170, 150, 60, 50);

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(30, 220, 60, 50);

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(100, 220, 60, 50);

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(170, 220, 60, 50);

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(30, 290, 60, 50);

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(100, 290, 60, 50);

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(170, 290, 60, 50);

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(100, 350, 60, 50);

        bttntambah.setText("+");
        bttntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttntambahActionPerformed(evt);
            }
        });
        getContentPane().add(bttntambah);
        bttntambah.setBounds(239, 150, 60, 50);

        bttnkurang.setText("-");
        bttnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(bttnkurang);
        bttnkurang.setBounds(240, 220, 60, 50);

        bttnbagi.setText("/");
        bttnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(bttnbagi);
        bttnbagi.setBounds(240, 290, 60, 50);

        bttnkali.setText("X");
        bttnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(bttnkali);
        bttnkali.setBounds(240, 350, 60, 50);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        label1.setText("Kalkulator ");
        jPanel1.add(label1);
        label1.setBounds(150, 30, 150, 20);
        label1.getAccessibleContext().setAccessibleName("label1");

        bttnsamadengan.setText("=");
        bttnsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnsamadenganActionPerformed(evt);
            }
        });
        jPanel1.add(bttnsamadengan);
        bttnsamadengan.setBounds(30, 400, 280, 50);

        bttnclear.setText("C");
        bttnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnclearActionPerformed(evt);
            }
        });
        jPanel1.add(bttnclear);
        bttnclear.setBounds(30, 340, 60, 50);

        btnkoma.setText(",");
        btnkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkomaActionPerformed(evt);
            }
        });
        jPanel1.add(btnkoma);
        btnkoma.setBounds(170, 340, 60, 50);

        btnpersen.setText("%");
        btnpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersenActionPerformed(evt);
            }
        });
        jPanel1.add(btnpersen);
        btnpersen.setBounds(310, 140, 70, 50);

        btnakar.setText("√");
        btnakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnakarActionPerformed(evt);
            }
        });
        jPanel1.add(btnakar);
        btnakar.setBounds(310, 210, 70, 50);

        btnpangkat.setText("^");
        btnpangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpangkatActionPerformed(evt);
            }
        });
        jPanel1.add(btnpangkat);
        btnpangkat.setBounds(310, 280, 70, 50);

        btnsisa.setText("Mod");
        btnsisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnsisa);
        btnsisa.setBounds(310, 340, 70, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 390, 470);

        setSize(new java.awt.Dimension(417, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       angka +="3";
        jTextTampil.setText(angka);
    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        angka +="1";
        jTextTampil.setText(angka);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       angka +="2";
        jTextTampil.setText(angka);

    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
      angka +="4";
        jTextTampil.setText(angka);

    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
       angka +="5";
        jTextTampil.setText(angka);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       angka +="6";
        jTextTampil.setText(angka);

    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
      angka +="7";
        jTextTampil.setText(angka);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
       angka +="8";
        jTextTampil.setText(angka);

    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
      angka +="9";
        jTextTampil.setText(angka);
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        angka +="0";
        jTextTampil.setText(angka);

    }//GEN-LAST:event_b0ActionPerformed

    private void btnkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkomaActionPerformed
         angka +=".";
        jTextTampil.setText(angka);
    }//GEN-LAST:event_btnkomaActionPerformed

    private void bttnsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnsamadenganActionPerformed
    switch(pilih){
   case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            jTextTampil.setText(angka);
            break;
   case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            jTextTampil.setText(angka);
            break;
   case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            jTextTampil.setText(angka);
            break;
   case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            jTextTampil.setText(angka);
            break;
  
   case 5:
               
           jumlah = Math.sqrt(angka1);
           angka = Double.toString(jumlah);
           jTextTampil.setText(angka);
           break;
           
   case 6 :
            jumlah = angka1 / 100;
            angka = Double.toString(jumlah);
            jTextTampil.setText(angka);
            break;
    case 7:
          angka2 = Double.parseDouble(angka);
          jumlah = Math.pow(angka1, angka2);
          angka = Double.toString(jumlah);
          jTextTampil.setText(angka);   
          break;
    case 8: 
          angka2 = Double.parseDouble(angka);
          jumlah = angka1 % angka2;
          angka = Double.toString(jumlah);
          jTextTampil.setText(angka);
          break;
    }//GEN-LAST:event_bttnsamadenganActionPerformed
    }
    private void bttntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttntambahActionPerformed
       angka1 = Double.parseDouble(angka);
       jTextTampil.setText("+");
       angka ="";
       pilih=1;
    }//GEN-LAST:event_bttntambahActionPerformed

    private void bttnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnkurangActionPerformed
       angka1 = Double.parseDouble(angka);
       jTextTampil.setText("-");
       angka ="";
       pilih=2;
    }//GEN-LAST:event_bttnkurangActionPerformed

    private void bttnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnkaliActionPerformed
        angka1 = Double.parseDouble(angka);
       jTextTampil.setText("*");
       angka ="";
       pilih=3;
    }//GEN-LAST:event_bttnkaliActionPerformed

    private void bttnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnbagiActionPerformed
       angka1 = Double.parseDouble(angka);
       jTextTampil.setText("/");
       angka ="";
       pilih=4;
    }//GEN-LAST:event_bttnbagiActionPerformed

    private void btnakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnakarActionPerformed
        angka1 = Double.parseDouble(angka);
       jTextTampil.setText("√");
       angka ="";
       pilih=5;
    }//GEN-LAST:event_btnakarActionPerformed

    private void btnpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersenActionPerformed
        angka1 = Double.parseDouble(angka);
       jTextTampil.setText("%");
       angka ="";
       pilih=6;
    }//GEN-LAST:event_btnpersenActionPerformed

    private void btnpangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpangkatActionPerformed
        angka1 = Double.parseDouble(angka);
       jTextTampil.setText("^");
       angka ="";
       pilih=7;
    }//GEN-LAST:event_btnpangkatActionPerformed

    private void bttnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnclearActionPerformed
        jTextTampil.setText(null);
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_bttnclearActionPerformed

    private void btnsisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsisaActionPerformed
        angka1= Double.parseDouble(angka);
        jTextTampil.setText("Mod");
        angka="";
        pilih=8;
    }//GEN-LAST:event_btnsisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton btnakar;
    private javax.swing.JButton btnkoma;
    private javax.swing.JButton btnpangkat;
    private javax.swing.JButton btnpersen;
    private javax.swing.JButton btnsisa;
    private javax.swing.JButton bttnbagi;
    private javax.swing.JButton bttnclear;
    private javax.swing.JButton bttnkali;
    private javax.swing.JButton bttnkurang;
    private javax.swing.JButton bttnsamadengan;
    private javax.swing.JButton bttntambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextTampil;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
